services:
  - type: web
    name: Chatserver
    env: python                   # ✅ must use this
    plan: free
    pythonVersion: 3.11.9         # ✅ this must be at this level
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
